export enum ChatUserServiceCommands {
  USER_CREATED = 'USER_CREATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PROFILE_CREATED = 'PROFILE_CREATED',
  TEAM_CREATED = 'TEAM_CREATED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  TEAM_DELETED = 'TEAM_DELETED',
}
